name: Cypress Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: unbutun-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Install depedencies
        run: yarn install

      - name: Run E2E tests 
        run: yarn cypress run
      
